import React, { useState } from "react";

import { Loader, Card, FormField } from "../components";

const RenderCards = (data, title) => {
  if (data?.length > 0) {
    return data.map((post) => {
      <Card key={post._id} {...post} />;
    });
  }
  // return (
  //   <h2 className="mt-5 font-bold text-blue-500 text-xl uppercase">{title}</h2>
  // );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [searchtext, setSearchtext] = useState("abc");
  const [allpost, setAllpost] = useState(null);

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[32px] text-gray-800">
          The Community Showcase
        </h1>
        <p className="mt-5 text-[16px] text-gray-600 max-w-[500px ]">
          Browse through a c ollection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div>
        {loading ? (
          <div className="flex justify-center items-center mt-20">
            <Loader />
          </div>
        ) : (
          <>
            {searchtext && (
              <h2 className="font-medium text-gray-600 text-xl mt-8">
                Showing results for{"  "}
                <span className="text-gray-900">{searchtext}</span>
              </h2>
            )}
          </>
        )}
      </div>
      <div className="grid lg:grid-col-4 sm:grid-col-3 xs:grid-col-2 gap-3">
        {searchtext ? (
          <RenderCards data={[]} title="No search results found" />
        ) : (
          <RenderCards data={[]} title="No posts found" />
        )}
      </div>
    </section>
  );
};

export default Home;
